[browser]
gatherUsageStats = false

[ui]
hideTopBar = true

[server]
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal" 